#!/usr/bin/python3
import sys, socket, getopt, threading, subprocess, traceback;

BLOCK   = 4096;
listen  = False;
command = False;
upload  = False;
execute = "";
target  = "0.0.0.0";
upload_destination = "";
port    = 5555;

def helper():
    print( "Netgato Net Tool" );
    print();
    print( "Usage: netgato -t target_host -p port" );
    print( "-l --listen [host]:[port]" );
    print( "-e --execute=file_to_run" );
    print( "-c --command ");
    print( "-h --help ");
    print( "-u --upload=destination - upon receiving connection upload a file and write to [destination]" );
    print();
    print();
    print( "Examples: " );
    print( "netgato -h" );
    print( "netgato -p 5555 -l -c" );
    print( "netgato -t 192.168.0.1 -p 5555 -l -c" );
    print( "netgato -t 192.168.0.1 -p 5555 -l -u=c:\\target.exe" );
    print( "netgato -t 192.168.0.1 -p 5555 -l -e=\"cat /etc/passwd\"" );
    print( "echo 'ABCDEFGHI' | ./netgato -t 192.168.11.12 -p 135" );
    sys.exit(0);

def client_handler(client_socket):
    global upload, execute, command, BLOCK
    if len(upload_destination):
        file_buffer = ""
        while True:
            data = client_socket.recv( BLOCK )
            if not data:
                break
            else:
                file_buffer += data
        try:
            with open( upload_destination, "wb" ) as file_descriptor:
                file_descriptor.write(file_buffer)
                file_descriptor.close()
                client_socket.send( ("Successfully saved file to %s\r\n" % upload_destination).encode("utf-8") );
        except:
            client_socket.send(("Failed to save file to %s\r\n" % upload_destination).encode("utf-8"))
    if len(execute):
        output = run_command( execute );
        client_socket.send(output.encode("utf-8"));
    
    if command:
        while True:
            client_socket.send((">").encode("utf-8"))
            cmd_buffer = ""
            while "\n" not in cmd_buffer:
                cmd_buffer += client_socket.recv(BLOCK).decode("utf-8")
            response = run_command( cmd_buffer )
            client_socket.send( response )

def server_loop():
    global target
    if not len(target):
        target = "0.0.0.0";
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as server:
        server.bind((target, port));
        print("Aguardando no endereço: ", (target,port));
        server.listen(50);
        while True:
            try:
                client_socket, addr = server.accept();
                threading.Thread(target=client_handler, args=(client_socket ,  )).start();
            except KeyboardInterrupt:
                break;
            except:
                traceback.print_exc();

def run_command(command):
    command = command.rstrip()
    try:
        output = subprocess.check_output(command, stderr=subprocess.STDOUT, shell=True);
    except:
         output = "Failed to execute command.\r\n"
    return output

def client_sender(buffer):
    global BLOCK
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as client:
        try:
            client.connect((target,port));
            print("Cliente se conectado ao: ", (target,port));
            if len(buffer):
                client.send(buffer);
            while True:
                recv_len = 1;
                response = "";
                while recv_len:
                    data      = client.recv(BLOCK).decode("utf-8");
                    recv_len  = len(data);
                    response  += data;
                    if recv_len < BLOCK:
                        break;
                print( response, end="" );
                buffer = input(" ");   # aqui eu vou ler o commandline do netcat
                buffer += "\n";
                client.send(buffer.encode("utf-8"));
        except:
            traceback.print_exc();
            print( "[*] Exception! Exiting." );
        finally:
            client.close();

def main():
    global listen, port, execute, command, upload_destination, target
    if not len(sys.argv[1:]):
        helper();
    try:
        opts, args = getopt.getopt(sys.argv[1:],"hle:t:p:cu:", ["help","listen","execute","target","port","command","upload"])
    except getopt.GetoptError as err:
        print( str(err) )
        helper()

    for o,a in opts:
        if o in ("-h","--help"):
            helper();
        elif o in ("-l","--listen"):
            listen = True;
        elif o in ("-e", "--execute"):
            execute = a;
        elif o in ("-c", "--commandshell"):
            command = True;
        elif o in ("-u", "--upload"):
            upload_destination = a;
        elif o in ("-t", "--target"):
            target = a;
        elif o in ("-p", "--port"):
            port = int(a);
        else:
            assert False,"Unhandled Option";

    if not listen and len(target) and port > 0:
        print("Digite Ctrl+d para iniciar");
        buffer = sys.stdin.read();
        client_sender(buffer);
    if listen:
        server_loop();

if __name__ == "__main__":
    main();



