#!/usr/bin/python3
import sys, socket, getopt, threading, subprocess, traceback;

listen  = False;
command = False;
upload  = False;
execute = "";
target  = "";
upload_destination = "";
port    = 0;

def usage():
    print( "Netgato Net Tool" );
    print();
    print( "Usage: netgato -t target_host -p port" );
    print( "-l --listen [host]:[port]" );
    print( "-e --execute=file_to_run" );
    print( "-c --command ");
    print( "-u --upload=destination - upon receiving connection upload a file and write to [destination]" );
    print();
    print();
    print( "Examples: " );
    print( "netgato -p 5555 -l -c" );
    print( "netgato -t 192.168.0.1 -p 5555 -l -c" );
    print( "netgato -t 192.168.0.1 -p 5555 -l -u=c:\\target.exe" );
    print( "netgato -t 192.168.0.1 -p 5555 -l -e=\"cat /etc/passwd\"" );
    print( "echo 'ABCDEFGHI' | ./netgato -t 192.168.11.12 -p 135" );
    sys.exit(0);

def client_handler(client_socket):
    global upload, execute, command
    if len(upload_destination):
        file_buffer = ""
        while True:
            data = client_socket.recv(1024)
            if not data:
                break
            else:
                file_buffer += data
        try:
            file_descriptor = open(upload_destination,"wb")
            file_descriptor.write(file_buffer)
            file_descriptor.close()
            client_socket.send( ("Successfully saved file to %s\r\n" % upload_destination).encode("utf-8") );
        except:
            client_socket.send(("Failed to save file to %s\r\n" % upload_destination).encode("utf-8"))
    if len(execute):
        output = run_command(execute)
        client_socket.send(output.encode("utf-8"))
    if command:
        while True:
            client_socket.send((">").encode("utf-8"))
            cmd_buffer = ""
            while "\n" not in cmd_buffer:
                cmd_buffer += client_socket.recv(1024).decode("utf-8")
            response = run_command(cmd_buffer)
            client_socket.send(response)


def server_loop():
    global target
    if not len(target):
        target = "0.0.0.0"
    server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    server.bind((target,port))
    print((target,port));
    server.listen(5)
    while True:
        client_socket, addr = server.accept()
        print("Recebido");
        client_thread = threading.Thread(target=client_handler, args=(client_socket,))
        client_thread.start()

def run_command(command):
    command = command.rstrip()
    try:
        output = subprocess.check_output(command,stderr=subprocess.STDOUT, shell=True)
        print(output);
    except:
         output = "Failed to execute command.\r\n"
    return output

def client_sender(buffer):
    client = socket.socket(socket.AF_INET, socket.SOCK_STREAM);
    try:
        print("Cliente se conectado ao: ", (target,port));
        client.connect((target,port));
        if len(buffer):
            client.send(buffer);
        while True:
            recv_len = 1;
            response = "";
            while recv_len:
                data      = client.recv(4096).decode("utf-8");
                recv_len  = len(data);
                response  += data;
                if recv_len < 4096:
                    break;
            print( responsexxxxxxxxxxxxxxxxx, end="" );
            buffer = input(" ");
            buffer += "\n";
            client.send(buffer.encode("utf-8"));
    except:
        traceback.print_exc();
        print( "[*] Exception! Exiting." )
        client.close()

def main():
    global listen, port, execute, command, upload_destination, target
    if not len(sys.argv[1:]):
        usage()
    try:
        opts, args = getopt.getopt(sys.argv[1:],"hle:t:p:cu:", ["help","listen","execute","target","port","command","upload"])
    except getopt.GetoptError as err:
        print( str(err) )
        usage()

    for o,a in opts:
        if o in ("-h","--help"):
            usage()
        elif o in ("-l","--listen"):
            listen = True
        elif o in ("-e", "--execute"):
            execute = a
        elif o in ("-c", "--commandshell"):
            command = True
        elif o in ("-u", "--upload"):
            upload_destination = a
        elif o in ("-t", "--target"):
            target = a
        elif o in ("-p", "--port"):
            port = int(a)
        else:
            assert False,"Unhandled Option"
    if not listen and len(target) and port > 0:
        print("Digite Ctrl+d para iniciar");
        buffer = sys.stdin.read();
        client_sender(buffer);
    if listen:
        server_loop()
main()



